# Generated by Django 4.1.3 on 2023-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_respostaquestionario_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='somatorio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
