# Generated by Django 4.1.3 on 2023-01-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_somatorio_remove_respostaquestionario_somatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somatorio',
            name='somatorio',
            field=models.IntegerField(),
        ),
    ]
