# Generated by Django 4.1.3 on 2023-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_resposta_somatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='somatorio',
        ),
        migrations.AddField(
            model_name='respostaquestionario',
            name='somatorio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
