# Generated by Django 4.1.3 on 2023-01-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_resposta_somatorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Somatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somatorio', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='respostaquestionario',
            name='somatorio',
        ),
    ]
